//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int ID_Bitacora { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora_Entrada { get; set; }
        public System.TimeSpan Hora_Salida { get; set; }
        public int ID_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
