//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID_Usuario { get; set; }
        public Nullable<int> ID_Colaborador { get; set; }
        public string Contrasenna { get; set; }
        public Nullable<bool> Privilegios { get; set; }
    
        public virtual Colaborador Colaborador { get; set; }
    }
}
